import java.util.Scanner;
import java.util.Random;
public class Number {

	public static void main(String[] args) {

		int n,answer,i=0,j=0;
		int score=0,y=0,q=1;
		final int MAX=100;
		Scanner sc=new Scanner(System.in);
		Random rand=new Random();
		answer=rand.nextInt(MAX)+1;
		while(q>=1) {
		while(j>=0) {
		System.out.println("You will get 5 chances to guess");
		while(i<5) {
		System.out.println("Guess the number generated by the computer between 0 to 100");
		n=sc.nextInt();
		if(n==answer) {
			System.out.println("The guess is correct , you earn one point");
			score+=1;
			answer=rand.nextInt(MAX)+1;
			i++;
		}
		else {
			System.out.println("The guess is wrong");
			if(answer<=10)
				System.out.println("The number lies between 0-10");
			else if(answer<=20)
				System.out.println("The number lies between 11-20");
			else if(answer<=30)
				System.out.println("The number lies between 21-30");
			else if(answer<=40)
				System.out.println("The number lies between 31-40");
			else if(answer<=50)
				System.out.println("The number lies between 41-50");
			else if(answer<=60)
				System.out.println("The number lies between 51-60");
			else if(answer<=70)
				System.out.println("The number lies between 61-70");
			else if(answer<=80)
				System.out.println("The number lies between 71-80");
			else if(answer<=90)
				System.out.println("The number lies between 81-90");
			else if(answer<=100)
				System.out.println("The number lies between 91-100");
			score+=0;
			i++;
		}

	}
		if(score>=1) {
			System.out.println("You win match with "+score+ " points");
		}
		else {
			System.out.println("You lose");
		}
		System.out.println("-------------------------------------\n ------------------------");
		System.out.println("Do you want to play again ,press 1 to continue else press 0");
		y=sc.nextInt();
		if(y==1) {
			j+=1;
			i=0;
			score=0;
			}
		else {
			System.out.println("End");
			j=-1;
			System.out.println("Do you want to start again press '1'  ");
			q=sc.nextInt();
			if(q==1) {
				j+=1;
				i=0;
				score=0;
			}
			
		}
			
		}
	}
}
}